### ISSUE TITLE
4.0.1 old version update loss of data in chunks

### ISSUE THREAD

**Issue by nebuxxx** [p3t3rix-vsmods/VsProspectorInfo#12]
updated from 3.2.0 to 4.0.0 and now to 4.0.1 and all the old chunks are unreadable: no prospectable resources found here.
is this related to the data loss in 4.0.0?

**Comment by GGGuenni** [comment]
Yes that's the bug that was fixed in 4.0.1
Sadly, the data can not be recovered if a chunk was prospected with version 4.0.0.
I hope it didn't cause too much damage

I will leave this issue open for a few days in case someone else with data loss has the same question.
Sorry again for the loss! I know such things can be a real bummer.

**Comment by mrgeoffkat** [comment]
Hi there, I too am having issues with this.  The majority of my old chunks are from 3.2.0, but I had just upgraded to 4.0.0 and today to 4.0.1.  Just realized all my pre 4.0 chunks are borked.  Is there any way to salvage the 3.2.0 data?  

Many thanks,

**Comment by nebuxxx** [comment]
> Yes that's the bug that was fixed in 4.0.1 Sadly, the data can not be recovered if a chunk was prospected with version 4.0.0. I hope it didn't cause too much damage
> 
> I will leave this issue open for a few days in case someone else with data loss has the same question. Sorry again for the loss! I know such things can be a real bummer.

there is no issue at all, a bummer yes for re fix the chunks, but sometimes bug happen. kind regards

**Comment by GGGuenni** [comment]
Closed because version 4.0.0 is over two weeks old now. There shouldn't be any more data loss questions.
