### ISSUE TITLE
Crash after 3rd sample

### ISSUE THREAD

**Issue by NehatLi** [p3t3rix-vsmods/VsProspectorInfo#15]
After taking the 3rd sample, my game crash. After reconnecting, the game work fine and even got the overlay infos!!(1.17.2)

**Comment by p3t3rix** [comment]
Does this happen continuously ? So does it crash after every third sample or just the first time ? Is it reproducible ?

**Comment by NehatLi** [comment]
I have only done it 2 time and crash 2 time. I have forgot to mention that I am on a server, maybe that the problem?

**Comment by p3t3rix** [comment]
could you attach the logfiles or maybe the stacktrace ? Did you have old readings on this server ? What is your language on the client ?

**Comment by NehatLi** [comment]
Here is my last crash log:
https://pastebin.com/A9HJrprr

**Comment by p3t3rix** [comment]
I guess from the log that your client language is french ? 
Is this on a fresh world/server where you haven't prospected with the mod or is it the first time you use the mod on that world ?
Is the prospecting on a new chunk or an existing one ?
Looks like a init/de-serialization bug in the ProspectInfo.GetMesage (probably because Values is not set properly). I can't verify nor fix it at the moment, but will look at it when i have the time (or maybe @GGGuenni is faster ;))

**Comment by NehatLi** [comment]
I'm French but my game is in English (for rp server) it's the first time I use this mod(I just bought the game 3 days ago) and it's all on "new chunks", I never prospected this chunks before.

**Comment by NehatLi** [comment]
I just try to use the previous version(4.0.1) even if i'm in 1.17.3 and the mod work, no crash!!
