### ISSUE TITLE
Losing some data of prospecting on server 1.17.11

### ISSUE THREAD

**Issue by LeonaLens** [p3t3rix-vsmods/VsProspectorInfo#22]
After rejoining the server, decimal numbers are no longer displayed, only integers.
Singleplayer works fine.

![image](https://user-images.githubusercontent.com/38184486/220662657-e595cc20-f099-4aac-8699-b07177fc01bf.png)

Data file from server looks like:
[vsprospectorinfo.data.txt](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/10808709/vsprospectorinfo.data.txt)

**Comment by GGGuenni** [comment]
Is this new to 1.17.11 or has this been a problem before?
Did you use other languages than English? If yes which? 

The file contains the decimal values so I don't know what the problem is here

**Comment by LeonaLens** [comment]
Didn't play on server before, so idk.
I'm using English. But server use ru, mb this is a reason?

Somehow it skip server values and write only message.

{
      "X":15617,
      "Z":16501,
      "Values":null,
      "Message":"Triangulated 3 traces of ore. Relative densities:\nHigh Ilmenite (1.4‰ absolute)\nVery poor Native copper (2.2‰ absolute)\nVery poor Hematite (0.2‰ absolute)\nMiniscule amounts of Sphalerite, Graphite\n"
   }
   
Singleplayer data looks like:
{
      "X":16000,
      "Z":15999,
      "Values":[
         {
            "Name":"game:ore-nativecopper",
            "PageCode":"item-nugget-nativecopper",
            "RelativeDensity":3,
            "AbsoluteDensity":6.7
         },
         {
            "Name":"game:ore-lignite",
            "PageCode":"ore-lignite",
            "RelativeDensity":3,
            "AbsoluteDensity":6.8
         },
         {
            "Name":"game:ore-bituminouscoal",
            "PageCode":"ore-bituminouscoal",
            "RelativeDensity":2,
            "AbsoluteDensity":1.3
         },
         {
            "Name":"game:ore-halite",
            "PageCode":"rock-halite",
            "RelativeDensity":2,
            "AbsoluteDensity":3.7
         }
      ],
      "Message":null
   }

P.S. Formatted for better reading

**Comment by LeonaLens** [comment]
Still an issue 😫

**Comment by p3t3rix** [comment]
I need to ask some questions otherwise we won't get further (and remember this is all voluntary on our side):
Same computer difference only if you start the dedicated server and connecting via client (if not what is your setup where the issue occurs)? 
Version is still 1.17.11 ? 
Any other mods are running (if so which) ? 
What steps can we do to reproduce it ?
Do you have a save file where we can reproduce it ?

**Comment by Wooza** [comment]
I looked a bit into this. The problem seems to be that the mod tries to parse the absolute density using the RegExp `([0-9]+,?[0-9]*)` where it expects a `,` as decimal separator, which obviously does not work in each locale. To make things even worse, the output generated by the ProPick itself does not adhere to the configured locale of the game, but uses the Runtime/System locale, [see here](https://github.com/anegostudios/vssurvivalmod/blob/fecc4d6c50c74e08a5dc7869eff7f967bc2577ac/Item/ItemProspectingPick.cs#L747).

So for example on my machine (German System, English Game) I get entries like this: `Very poor Native copper (3,9‰ absolute)`, where `,` as a separator works. Looking at the uploaded file, there are some legacy messages that have a `.` as a separator, which is why I assume it only recognizes the part that comes before the decimal separator.

Scraping locale dependent output is always a bit hacky. 
One possible (hacky) fix would is to include the System decimal separator when constructing the Regex,
so something like `'([0-9]+' + escapedSeparator + '?[0-9]*)'`, similar to [this answer](https://stackoverflow.com/a/49873129) on SO

@GGGuenni @p3t3rix  I can give it a try if you think this is a reasonable fix.

Edit:
Now that I'm thinking about it, a better solution to the general problem of parsing the chat output of the ProPick would be to refactor the ProPick itself, i.e., split `PrintProbeResults` into a method which just computes the densities and returns some kind of result and put the conversion of that result to a string in a different method. If understand the harmony lib used in this project correctly, then one could use it to grab the result of the ProPick and no longer rely on the chat output (+ also could reuse the formatting code from the ProPick to display the information on the map). But that is probably a lot more work 😅

**Comment by GGGuenni** [comment]
Wow, only the separator is in system locale?! What a mess...

But good find! and sure sounds like a reasonable fix 
The whole chat stuff is "hacky" in my eyes anyway

> grab the result of the ProPick and no longer rely on the chat output

Sadly that's not possible. At least I didn't get it to work. The reason is that this mod is supposed to stay client-side only. Trying to patch the ProPick requires server-side code which would make everything a lot easier but also would require every server to install this mod for it to work.

**Comment by p3t3rix** [comment]
The question is are there that many decimal seperators? We could extend the regex to include ',' as well as '.'.  This could of course lead to problems when the numbers would be grouped by digit (like 1,000,000.23) but i am not sure that is currently a case we need to consider.

**Comment by LeonaLens** [comment]
>Same computer difference only if you start the dedicated server and connecting via client (if not what is your setup where the issue occurs)?

If I start the dedicated server on my own computer there is no such issue (tested right now) 
So issue ocurs only on server where I'm playing right now. (mb need to test another servers too?)
I tested using same language as server on client, it didn't help. Also I tested to start the dedicated server on my own computer with config   "ServerLanguage": "ru", still works fine. (mine OC is Win10)
So my next guess about reasons is that those server is on Linux + using "ru" localization file. (heared sometimes it matters)

>Version is still 1.17.11?

Yes.

>Any other mods? 

Yes, lots of them. List of them below.
[Mods.txt](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/10911793/Mods.txt)

>What steps can we do to reproduce it? 

Can't really find this steps. I will ask owner of server if he could help to test this on his server (it's private and passworded only by invites) 

>Do you have a save file where we can reproduce it? 

Nope, I'll ask an owner this too. But it could take a while he's on vacation right now.

Anyway, Wooza said smart things, looks very similar to our issue, as I understand.

P.S. I understand why you want it to stay only client-side mod.
But if this mod will became a server-side it will be the first "must have" mod on all servers. 🤣 Thanx for mod btw!
P.P.S. Sorry of my English. I'm not native, hope you'll understand what I mean.

**Comment by p3t3rix** [comment]
@LeonaLens thanks for reporting this bug, could you try version 4.1.3 to see if the issue still persists ?

**Comment by Bulisek** [comment]
> 

Hi, I have this issue too, and I tried version 4.1.3 but the game crashed. I am using windows in the cs_CZ localization, which uses ',' as a decimal point. A crash log is attached.
[Vintage story crash.txt](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/10923939/Vintage.story.crash.txt)

**Comment by Wooza** [comment]
@p3t3rix it seems like I made things worse. Can you pull 4.1.3 from the moddb before more people run into this issue?

@Bulisek can you post (a part) of your vsprospectorinfo.data file?

**Comment by Bulisek** [comment]
After removing the file and making a new prospecting with an empty result, it works fine.
But after sucessfull prospecting and leaving and trying to load the game again it crashed again.
Part of the original file content is here:
'[{"X":15641,"Z":15610,"Values":[],"Message":null},{"X":15658,"Z":15494,"Values":null,"Message":"Triangulated 2 traces of ore. Relative densities:\nVery high Cassiterite (0.1‰ absolute)\nVery poor Cinnabar (0‰ absolute)\nMiniscule amounts of Hematite, Halite, Alum\n"},{"X":15654,"Z":15622,"Values":null,"Message":"Triangulated 3 traces of ore. Relative densities:\nUltra high Cassiterite (0.2‰ absolute)\nVery poor Cinnabar (0.1‰ absolute)\nVery poor Emerald (0.1‰ absolute)\n"},{"X":15657,"Z":15623,"Values":null,"Message":"Triangulated 2 traces of ore. Relative densities:\nVery high Cassiterite (0.2‰ absolute)\nVery poor Cinnabar (0.1‰ absolute)\nMiniscule amounts of Emerald\n"},{"X":15655,"Z":15623,"Values":null,"Message":"Triangulated 2 traces of ore. Relative densities:\nUltra high Cassiterite (0.3‰ absolute)\nVery poor Cinnabar (0.1‰ absolute)\nMiniscule amounts of Emerald\n"}]'

New file content is here:
'[{"X":15641,"Z":15610,"Values":[],"Message":null},{"X":15650,"Z":15609,"Values":null,"Message":"Triangulated 2 traces of ore. Relative densities:\nUltra high Ilmenite (2.7‰ absolute)\nVery poor Sphalerite (0.1‰ absolute)\nMiniscule amounts of Emerald\n"}]'
[Crash.txt](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/10924370/Crash.txt)

**Comment by p3t3rix** [comment]
> @p3t3rix it seems like I made things worse. Can you pull 4.1.3 from the moddb before more people run into this issue?
> 
> @Bulisek can you post (a part) of your vsprospectorinfo.data file?

Pulled the release, weird i tried it locally and it worked. At least it didn't crash :/

**Comment by Wooza** [comment]
Some observations that I made:
1. Both of the reported `vsprospectorinfo.data.json` files contain entries where `message` is not null. If I understood the code correctly, this is a legacy format, where the entire message is stored, but newer versions store the parsed information instead. I do not understand why these are still there, because they should be converted to the new format as soon as the file is loaded/stored with a newer version of the mod 🤔.
2. Three pieces of information are relevant for parsing the ProPick output: 
   1. the system locale of the server OS, which is used to format the absolute densities.
   2. the system locale of the client OS, which is used to parsed the absolute densities.
   3. the client locale of the game, which is used to find the proper i18n template (`Lang.Get...`) to know where certain information is located within the output string.
3. I think the original problem described by LeonaLens happens when there is mismatch between i. and ii., e.g., `.` on server and `,` on client: `0.5` is parsed as `5`. This can only happen in multiplayer.
4. The regex that I changed is only used to locate the absolute density number in a legacy message, but doesn't address the problem in 3.

**Comment by Bulisek** [comment]
If I understand the code correctly, the problem in bullet 3. is causing a parsing error, so it saves the message as a string instead. That way, it can try again next time, when the problem is resolved.
Bullet 3. exactly describes my case. But I think that 0.5 is parsed as null, and that's the problem.

**Comment by Wooza** [comment]
Changing the process locale with `CultureInfo.DefaultThreadCurrentCulture = CultureInfo.CreateSpecificCulture("cs-CZ")` allowed me to reproduce the crash. 
Let's take the following string as an example: `Very high Cassiterite (0.1‰ absolute)`.
The old regex found `0` as the first match which is parsed to `0` with `cs-CZ`.
The new regex finds `0.1` as the first match, which throws an exception with `cs-CZ`. Interestingly it is parsed as `1` with `de-DE`.

**Comment by Wooza** [comment]
I implemented another fix and zipped it up if you want to try it. @LeonaLens @Bulisek 
[ProspectorInfo-4.1.3-pre.zip](https://github.com/p3t3rix-vsmods/VsProspectorInfo/files/10943631/ProspectorInfo-4.1.3-pre.zip)

**Comment by Bulisek** [comment]
It works for me. Good work @Wooza

**Comment by LeonaLens** [comment]
> 2. Three pieces of information are relevant for parsing the ProPick output:
>    
>    1. the system locale of the server OS, which is used to format the absolute densities.
>    2. the system locale of the client OS, which is used to parsed the absolute densities.
>    3. the client locale of the game, which is used to find the proper i18n template (`Lang.Get...`) to know where certain information is located within the output string.

MB even 4?
4. the server locale of the game server.

Our's pieces will be nuts:
1 eng
2 ru
3 eng
4 ru

>I implemented another fix and zipped it up if you want to try it.

Tested right now. Looks like all goes fine, even some chunks prospected before have full values (some not, but it's not an issue to go and prospect them once more) Data file looks amazing! Thanx! @Wooza 😘

**Comment by p3t3rix** [comment]
i created a new release 4.1.4 which includes the fix
